### ISSUE TITLE
Search users (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#11]
> As a student,
So I can find my peers,
I want to search for others by name.

> As a teacher,
So I can find students to add to my cohort,
I want to search for students by name.

**Requirements**

- Search input to enter a user's _first name_
- A list of results
- Clicking on a result takes the user to that profile

--

**GET /users**
**Headers**
`Authorization: "Bearer <token>"`

**Query parameters**
`first_name`

**Example:** `/users?first_name=nathan`

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "users": [
      {
        "id": int,
        "cohort_id": int | null,
        "first_name": string,
        "last_name": string,
        "email": string,
        "role": string<"STUDENT", "TEACHER">,
        "biography": string | null,
        "github_url": string | null
      }
    ]
  }
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/10

**Comment by ben-corbin** [comment]
Proposed sub tasks that we will PR for each:

- [ ] Search bar
- [ ] Search button
- [ ] Get users
- [ ] Display users
- [ ] Link to take teacher to user profile

**Comment by ben-corbin** [comment]
We would be doing branches for each of these items too I assume
