### ISSUE TITLE
Bug: First comment display shows incorrect author

### ISSUE THREAD

**Issue by mikemherron** [boolean-uk/team-dev-client#128]
When adding a comment to a post, the unexpanded preview that only shows the first comment shows the wrong author. See the screenshot below - the comment has been made by Mike:

![image](https://user-images.githubusercontent.com/15673068/167575309-e2c4ddd3-62d1-4788-b1fe-50e14d5545d0.png)

But when the show all view is collapsed, it shows Dabe has made the comment:
![image](https://user-images.githubusercontent.com/15673068/167575341-adba8146-7154-4396-956b-f4722db16c28.png)

**Comment by alsyoufomar** [comment]
problem fixed
