### ISSUE TITLE
Bug: Horizontal scroll bar shown on home page

### ISSUE THREAD

**Issue by mikemherron** [boolean-uk/team-dev-client#132]
See screenshot:

![image](https://user-images.githubusercontent.com/15673068/167579652-89383403-36cf-40b7-a68d-29ea36e4d071.png)

A horizontal scroll bar has been added when it is not needed.

**Comment by ben-corbin** [comment]
@mikemherron I can't replicate this issue on any browser window size. Can you give me a shout when you get a moment so that we can discuss. Thanks.
