### ISSUE TITLE
View Posts (client)

### ISSUE THREAD

**Issue by mikemherron** [boolean-uk/team-dev-client#15]
- [x]  Posts should be displayed on the home page whenever a user (teacher or student) logs in.

- [x]  the most recent 100 posts should be displayed

- [x]  Posts should display the message,first and last name (this is on Profile in the db) and time the post was made

- [x]  time should be displayed in a relative style (i.e. "2 hours ago")
Suggested library for this: https://date-fns.org/

**Comment by alsyoufomar** [comment]
As a user,
So that I see what has been posted,
I want to see all the posts when I log in.


GET/posts
Headers
```Authorization: "Bearer <token>"```

See the server response samples to handle responses: [https://github.com/boolean-uk/team-dev-server/issues/29](url)
