### ISSUE TITLE
Create Cohort

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#165]
> As a teacher,
So I can begin onboarding a new class,
I want to create cohorts.

**Requirements**

- "Create cohort" button, no further information required
- Only users with a `role` of `"TEACHER"` can access / submit this form

--

**POST /cohort**
**Headers**
`Authorization: "Bearer <token>"`
No body required

**201 Response body**
```json
{
  "status": "success",
  "data": {
    "cohort": {
      "id": int
    }
  }
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/7

**Comment by Alex90Jennings** [comment]
CREATE A COHORT

1) Take the user log in data from the log in form and save to a state in app.js as [loggedInUser, setLoggedInUser] = useState(null)
2) Pass the state through to the header component/useContext to make the state globally available
3) Conditionally render the Add Cohort button
4) Add functionality to the Add Cohort button with an eventListener
5) Form to appear with cohort details (such as cohort number)
