### ISSUE TITLE
Search Students

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#166]
> As a student,
So I can find my peers,
I want to search for others by name.

> As a teacher,
So I can find students to add to my cohort,
I want to search for students by name.

**Requirements**

- Search input to enter a user's _first name_
- A list of results
- Clicking on a result takes the user to that profile

--

**GET /users**
**Headers**
`Authorization: "Bearer <token>"`

**Query parameters**
`first_name`

**Example:** `/users?first_name=nathan`

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "users": [
      {
        "id": int,
        "cohort_id": int | null,
        "first_name": string,
        "last_name": string,
        "email": string,
        "role": string<"STUDENT", "TEACHER">,
        "biography": string | null,
        "github_url": string | null
      }
    ]
  }
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/10

**Comment by sigristarisa** [comment]
Worked on the steps of how we could accomplish the task (see Notion).
Added codes in the Notion page that might be helpful as a reference.
[Notion: Server Search Students](https://www.notion.so/Search-Students-86f772c3c8ca4e8c9189910ee6aaec76)
