### ISSUE TITLE
Add comments to posts (client)

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-client#175]
## User Story
As a user, so I can interact with others, I want to be able to comment on posts.

## Tasks
Only the first comment is shown by default, along with the number of comments
Users can click a "Show all comments" button to expand the list of comments
Comments should have smaller font size than posts
Comments should show the users name and the time the comment was made.

**Comment by Hoolio333** [comment]
- Create CommentForm.js used inside PostPage.js to handle the comment submit
- Add a createComment function on PostPage.js
- Use preventDefault to remove behaviour of form
- Console.log(res) (from .then) to check the response is working and the data being sent  
- Console.log(data) (from .then) to check the response is working
- Add an useState (comment, set comment) - sending the form data to the api
- Add a userState (comments, setComments) - putting all the comments in the array 
- Map through the array of comments to match the oldest comment to the post (which will be seen)
- As all the comments are in an array, we can then display all if a user clicks requesting to see all the comments
- To get all these comments we'll create a button.  When user clicks on the button, then an event occurs which will display all the comments in the array
- The Comments will show the users name and the time the comment was made as this information is in the array from the data response (the schema was previously amended on server ticket to ensure this could occur).
- Filter & Map might be needed to ensure all the comments don't show on every post but only on the right ones.
- Use CSS to show Comments having smaller font size than posts
