### ISSUE TITLE
Cohorts can be created with names

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#191]
Requirements
```
-Add Cohort button now takes the user to a new "Add Cohort" Page
-On that page, the user is presented with a form with a single input for now - "Cohort Name".
-The Cohort Name should be unique - if it’s not, user should see an error message.
-Pressing Save takes the user to the view Cohort Page for the newly added cohort.
```

Extends work on https://github.com/boolean-uk/team-dev-client/issues/165
Dependent on work on https://github.com/boolean-uk/team-dev-server/issues/119

**Comment by Alex90Jennings** [comment]
![image](https://user-images.githubusercontent.com/97463171/176225662-d6b1cd02-0d22-4798-a6d7-652b8fcf292d.png)

**Comment by dearshrewdwit** [comment]
Can you add some example requests and responses?

LGTM
