### ISSUE TITLE
STUDENTS can see their cohort members [3]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#192]
Requirements

-When user logs in and they are a student, on the right hand side add a new header "Cohort X students" , replacing X with the Cohort name
-A sub-heading should display the number of students in that Cohort
-Under that heading a new table should display all the other students in the same Cohort (the currently logged in student should also be displayed).
-For each student display their firstname, last name and profile image. When clicking the student, the user should be taken to their profile page.

**Comment by Anicaaa** [comment]
<img width="968" alt="Screenshot 2022-07-04 at 16 38 59" src="https://user-images.githubusercontent.com/75957784/177185927-ecd4fbe7-340a-480c-a6ec-de99cf95caf1.png">

**Comment by Anicaaa** [comment]
<img width="968" alt="Screenshot 2022-07-04 at 17 20 19" src="https://user-images.githubusercontent.com/75957784/177191505-a8e5817e-0bfe-4d63-9aa9-b38b3b16ea2e.png">
