### ISSUE TITLE
As a teacher, so that I can quickly see how many classes are running, I want to see a list of Cohorts when I log in [3]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#193]
As a teacher, so that I can quickly see how many cohorts there are, I want to see a list of Cohorts when I log in

Requirements

- Show a list of cohorts on right hand side of home page
- Each cohort item in the list should be clickable - when clicked, the component renders that list of cohort members, without the page refreshing or navigating to a different page. 
- Each cohort member should be clickable - when clicked, you show a summary of the student profile (don't navigate to the profile)
- there should be a button to go back to the list of cohorts.

**Comment by Auenc** [comment]
> There will be a button to render CohortPreviewList always visible.

By this, do you mean a button to go back to the initial view of all Cohorts? I'm assuming you do, just want to be clear :)

**Comment by Auenc** [comment]
Okay great, looks good to me! Good job!
