### ISSUE TITLE
Users have profile images [3]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#194]
Requirements

- Users are assigned a default profile image when none is specified
- On register (or on edit profile page) users can provide a URL to an image they want to use as their profile image
- The profile image (place holder or user defined) should be displayed in the top right of the application when they are logged in.
- On the profile page, a larger version of the user image should be displayed
- On the posts list, the users image should appear alongisde the posts as a thumbnail. The same for any post comments.

**Comment by sigristarisa** [comment]
We have planned the steps we want to take for this issue:
## Task

- in UserForm.js, add a new <TextField />
- in Profile.js, add a new <TextField />
- in the Header.jsx, add a <div> and a <img> next to the “Profile” button and render profile image
  💡 (Or would it be better to add the <Link> to the <img>??)

- in Profile.js, add a <div> and a <img> above the profile text
- in PostsPage.js, render the image in the <li> tag by {post.user.profileUrl}
- in Comment.js render the image in the <li> tag by {post.user.profileUrl} wait for CLIENT SIDE

Notion: [Notion](https://www.notion.so/User-have-profile-image-7e179f70a1e442a9932cd567a65496db)
