### ISSUE TITLE
Login user automatically after user registers. [5]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#198]
As a new user, so that my initial experience is better, I want to be logged in automatically when I register a new account.

Requirements

-At the moment, we simply display "Status Success" when a user registers - instead, log that user in automatically and take them to the home page.
-Message should be displayed such as "Welcome to Cohort Manager 2.0!" - only in the case of that first login.

**Comment by sigristarisa** [comment]
- in RegistrationPage.js, we will receive ``createdUser`` data with a token
- set the token in the local storage
- set the logged in User data with ``useContext``
- navigate to ``/posts``
- in RegistrationPage.js, change the message to “Welcome to Cohort Manager 2.0!"

**Comment by Creatorrr1** [comment]
Planning
GOAL = As soon as the user registers, the user is automatically logged on
1) I'd primarily focus on the function that's being called by the submit button for register
2) I would create another function that would take in the user.email and user.password from the user state in register.js
3) A post request (/login path) would be made to the server side which takes in the data and once login is successful it would then navigate to the post page immediately.

**Comment by dogezen** [comment]
@Creatorrr1 -> make sure to only proceed with calling the function in step 2. (and hence do step 3) only if the registration is indeed successful.

**Comment by dearshrewdwit** [comment]
@sigristarisa @Creatorrr1 @Alex90Jennings @d-username  Is this still waiting for a review?
