### ISSUE TITLE
Bug: User trying to login without creating an account [1]

### ISSUE THREAD

**Issue by Auenc** [boolean-uk/team-dev-client#212]
If a user tries to login without creating an account, the server will return an error - however - this error is not displayed to the user.

We should display the message returned by the server to the user.

**Comment by dearshrewdwit** [comment]
![Screenshot 2022-07-01 at 09 26 37](https://user-images.githubusercontent.com/13719921/176856243-4a3fa572-1cfe-4c2c-a46f-f17e1a61f267.png)
