### ISSUE TITLE
BUG: navigating to my profile as a student logs a 403 to the console [1]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client#227]
![Screenshot 2022-07-05 at 11 38 33](https://user-images.githubusercontent.com/13719921/177310174-cdcadfd7-5590-4bb9-af9f-fa393cdaf49e.png)

Steps to replicate
- sign in as a student
- click on the profile button
- see error in console.

Expected behaviour
- no 403 response
- As a student, I don't see cohort information about other students in my profile.

**Comment by Alex90Jennings** [comment]
The /cohort end point is run with the validateTeacherRole function, so all access is blocked for STUDENTs. 

I don't know which team wants to implement this change, I think teacher admin.

If the desired outcome is for TEACHERs to fetch the cohort information, then it would just require an if statement in the useEffect function to filter by role. (client side - src - component - profile - profile.js - line 32-39)

If the desired outcome is for STUDENTs to be able to fetch the cohort information, then it would require the validateTeacherRole to be removed from the router.get('/cohort'), but that could have a knock on effect that means that a STUDENT would be able to access information that should be restricted.

**Comment by dearshrewdwit** [comment]
Thanks @Alex90Jennings - seems reasonable as a solution.

Reassigning this to Team TA.
