### ISSUE TITLE
when a teacher checks notes of a student, the notes should be ordered by date and have the option of adding a note [3]

### ISSUE THREAD

**Issue by Alex90Jennings** [boolean-uk/team-dev-client#229]
- clicking button shows /users/12/notes (only available to teachers): a list of notes ordered by date (most recent at the bottom), with teacher name and timestamp and note content
   - render a list of notes in order of date
   - there should be a textarea element at the bottom of the list to add a new note to the student that is added to the list immediately
   
   
   USER STORY 
   
   So a teacher can update the progress of a student,
They should be able to see previous notes and when they were created,
And make another note immediately

**Comment by sigristarisa** [comment]
- add ``TextArea``above the note ``ul`` in ProfileNote.js
- create ``useState`` for notes that takes in the input of ``TextArea``
- create ``handleNotesChange`` function that handles the input of ``TextArea``
- create a button that creates a new note
- create ``handleNotesSubmit`` function that makes a post request
- once we submit the new note, do a get request to render the new note
