### ISSUE TITLE
notes can be edited or deleted, and show `edited at [timestamp]` next to the timestamp if edited [3]

### ISSUE THREAD

**Issue by Alex90Jennings** [boolean-uk/team-dev-client#230]
- notes can be edited (and show edited at [timestamp] next to the timestamp if edited)
   - notes can be deleted by any teacher
   
   USER STORY
   
   In case a teacher makes a mistake,
   Highly unlikely it's true,
   They should be able to change or delete their notes

**Comment by Alex90Jennings** [comment]
PLAN

render a button for delete on each note
check that loggedInUser.role is TEACHER
handleClick for delete - client.delete (note/:id)

render a button for edit on each note
handleClick for edit - client.edit (note/:id). 
set isEdited for that note to true
if isEdited = true, conditionally render a p tag
fetch the updatedAt from the DB ({formatDate(Date.parse(comment.createdAt))})

**Comment by dearshrewdwit** [comment]
Sounds reasonable.

What component(s) are you proposing you'll need to build?
What state do you need to keep in the components?

**Comment by Alex90Jennings** [comment]
A post can be edited and deleted, so we will be using the posts as a template, to keep the components consistent.
