### ISSUE TITLE
List cohortExcercise [5]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-client#239]
##User Story:

As a student, I want to see all the available cohort exercises, grouped by Unit.

##Requirements:
   - /profile/:id/exercise 
   - fetch the list of cohort exercise
   - render a list of the exercise in a ul

![image](https://user-images.githubusercontent.com/97617284/178455741-4c7323e9-55a3-4859-a4c8-32f14fe5b256.png)

**Comment by sigristarisa** [comment]
Thank you for the feedback.

**Update path to ``: /profile/:id/exercises``**
=> we will!

**1. What endpoint do you need to use to get cohort exercises?**
=> the endpoint is ``cohort/:id/cohortExercises``

**2. What is the current response data format when requesting cohort exercises?**
=> the response data is an array of ``cohortExercise``, which is an object that contains ``id``, ``cohortId``, ``exerciseId``.
At the moment we cannot access the ``exercise`` data property through ``cohortExercise``, so we need to refactor the server side...

**Comment by dearshrewdwit** [comment]
Ok. Update the `GET cohort/:id/cohortExercises` endpoint to include exercise and unit data.
