### ISSUE TITLE
Excercises are linked to Github repo[3]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-client#241]
User Story:

As a user, I want to be directed to the Github repo, when I click on each exercise.

Requirements:

- make links for rendered ul element
- Exercises are clickable and go straight to the GitHub repository page.

**Comment by sigristarisa** [comment]
- for each cohort exercise list item, add a ``<a>``tag
- get ``githubUrl`` through ``exercise``
- add  ``githubUrl`` to ``<a>`` ``href``
