### ISSUE TITLE
As a user, so I can see what's going on in the community, I want to see a list of posts when I log in.#30

### ISSUE THREAD

**Issue by ning905** [boolean-uk/team-dev-client#264]
1. When a user logs in, they will be directed to /posts route.

2. When /posts is rendered for the first time, send GET request to http://localhost:4000/posts retrieve a list of posts, with the jwt token in the HEADER.

```HEADER: {Authorization: Bearer <token> }```	
Response sample: 
```{
  "status": "success",
  "data": {
    "posts": [
      {
        "id": 1,
        "content": "Hello world!",
        "author": {
          "id": 5,
          "cohortId": null,
          "firstName": "Nathan",
          "lastName": "King",
          "email": "ngk2@gmail.com",
          "bio": "Hello world",
          "githubUrl": "https://github.com/vherus",
          "role": "STUDENT",
	“createdAt”: “String”,
	“updatedAt”: “String”,
        }
      }
    ]
  }
}
```
3. Create function formatTime to convert time from string to a human-readable format (e.g. "2 hours ago", "less than a minute ago", "Aug 19th"). 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
- Within 1 min, display “less than a minute ago”;
- Within 1 hour, display “xx minutes ago”;
- Within 1 day, display “xx hours ago”;
- Within the same year, display date “dd Month”;
- Else, display date “dd Month yyyy”

4. Combine the GET request, formatTime, setPosts() into one function renderPosts, which can be reused to update the list of posts shown on the page.

5. Create PostItem jsx element, which dsiplays the content, student/teacher name, and the time the post was made.
![Screenshot 2022-09-13 at 16 35 50](https://user-images.githubusercontent.com/95832213/189944824-e3187c43-40cb-4881-be59-11022f88f7a8.png)

6. Render the list of posts. Pass in each post object as props to PostItem.
7. If the posts array is empty, instead of PostItem elements, display text “No posts at the moment” on the page.

**Comment by Auenc** [comment]
Looks good to me!
