### ISSUE TITLE
#31 As a user, so I can share my progress with others and take part in the community, I want to be able to make posts

### ISSUE THREAD

**Issue by mnmin** [boolean-uk/team-dev-client#265]
## User Story
As a user, so I can share my progress with others and take part in the community, I want to be able to make posts

## Tasks
FrontEnd:

1) Importing and using the useState to keep track of the created a post input
2) Use the response from the API to display the response from create Post function

Example response
```Authorization: Bearer &lt;token&gt;

{
  "content": "Hello world!"
}

{
  "status": "success",
  "data": {
    "post": {
      "id": 1,
      "content": "Hello world!"
    }
  }
}
 ```
3) Have the submit button working with a submit handler
4) The submit handler is sending a URL post request to the API.
5) The request to the api has header (containing authorization) and  body (data).

**Comment by Auenc** [comment]
Minor issue with the example request and response. You request has the content `Hello world!` but your response has `Hello!`. Might be a good idea to update that just so it's not confusing when you come to do the work.
