### ISSUE TITLE
#27 CLIENT SIDE As a teacher, so I can begin onboarding a new class, I want to create cohorts

### ISSUE THREAD

**Issue by richard-mattinson** [boolean-uk/team-dev-client#266]
# User Story
As a teacher, so I can begin onboarding a new class, I want to create cohorts

- Add a new "Create cohort" button to the application. This should be displayed for teachers only.
- For now, all the button needs to do is create a new Cohort, there is no other information required.
- This may require adding the ability to register as either a teacher or a student. For now, we can just add a simple radio button selection on the sign up for. Later we'll implement something more sophisticated.

## Tasks
**CLIENT**
- "Conditional render" so that only teacher can see a create cohort / students won't see the button
- Check if user role is a teacher by including this package: [Decode token](https://www.npmjs.com/package/jsonwebtoken) 
- Create Cohort button will simply increment the current Cohort id by 1 automatically when pressed
- Handle submit function 
- Teacher can then click button which will send a post request to `/cohort`. (No data required only auth header)
- Create radio buttons that allows you to sign up as student or teacher
- Create [sample responses](https://hubertlemczak.github.io/team-dev-api/#/cohort/createCohort)
- Make sure request and response schema match the current format

**Comment by Auenc** [comment]
Could you add an example request? It would be good to see:
- The type of request (GET, POST, ETC)
- The URL of the endpoint
- any data that needs to be passed to the endpoint, either via the URL or by the body
