### ISSUE TITLE
#32 As a teacher, so I can organise our students, I want to assign students to a cohort

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#267]
## User Story
As a teacher, so I can organise our students, I want to assign students to a cohort

## Tasks

- (Create new page with route `/enroll-student`?)
- Display all users (with role STUDENT) in a list
![image](https://user-images.githubusercontent.com/100080535/189922151-a6c0ea4d-a859-4a88-8ed0-68a8c4985a2c.png)
- Add to cohort onclick patch to `/user/:id` with selected cohort_id in body
- [API Response](https://hubertlemczak.github.io/team-dev-api/#/user/asd)
- Cohort must be selected checks
- Display success e.g. Update current cohort or display success message
- Display errors e.g. Unable to add user to cohort

**Comment by Auenc** [comment]
Looks good to me!
