### ISSUE TITLE
#47 As a user, so I can fix mistakes, I want to be able to edit my posts

### ISSUE THREAD

**Issue by Noemi890** [boolean-uk/team-dev-client#284]
<img width="613" alt="Screenshot 2022-09-14 at 18 53 51" src="https://user-images.githubusercontent.com/94084046/190230690-11e057d7-5de0-430d-bf89-d60cfcb47bb8.png">

- Adding an edit link in the itemPost component
- Make sure it renders JUST when the userId (will get it from the token saved in localStorage) matches with the userId linked in the post.
- When the Edit button is clicked, a text area will appear where the content of the post is (at the bottom will display a save link to save the changes) allowing the user to modify the content, saving everything into a React State. reference(https://reactjs.org/docs/forms.html#controlled-components)
- Once the user click on the save link, a handle function will run, requesting a change to the server.

```
Example request: 

const res = await fetch(`/post/${id}` {
	method: ‘PATCH’
           …………..
})
```

**Comment by vherus** [comment]
Great plan!

Make sure the backend portion also verifies the correct user ID, don't trust the client to get it right. Proceed :)
