### ISSUE TITLE
#54 Improve the styling of user list on cohort enrolment page

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#298]
## Tasks

- Research mui components to redesign the current styles for the `UserListItem` component
   - Use the select dropdown
   - Use the button component
- Use similar stying to the posts page post comonent

**Comment by vherus** [comment]
> - Research mui components to redesign the current styles for the UserListItem component

Research is part of the planning process rather than the dev process (although it does happen there too), so I'd spend some time looking into MUI and update this issue with some concrete details about what you'll use from MUI
