### ISSUE TITLE
#40 As a teacher, so I can check students are correctly registered, I want to see what students belong to each Cohort

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#315]
## Tasks
- Create new `/cohort/:cohortId` route
- Render a page with the cohort name and list of users
- If cohort has no users, conditionally rendered button that will take user to enrolment page
- Mapped users will be linked to their profile page when clicked
![image](https://user-images.githubusercontent.com/100080535/191226169-183d8282-2c92-4737-a6b2-4def08072042.png)

**Comment by vherus** [comment]
Nice! Proceed
