### ISSUE TITLE
As a user, so I can see popular posts, I want the most popular post of the week to be highlighted.#49

### ISSUE THREAD

**Issue by ning905** [boolean-uk/team-dev-client#351]
1- Create a new state “postOfTheWeek” in the PostPage.
2-  Extract from the posts state all the posts that are created within 7 days. Use array.forEach() to find the most popular one from the array, regarding the number of likes and comments. Splice this object from the posts array, so it does not get rendered in the normal post list.
3- Create a “PostOfTheWeek” component, which has a PostItem component inside, with extra margins on top and bottom as well as some decorations. Pass in the  “postOfTheWeek” as props. Place the component on top of the post list.

**Comment by vherus** [comment]
Which side of the application will be responsible for determining what defines a "post of the week"? Will it be a backend calculation or frontend?

If it's frontend, what does that algorithm look like?

**Comment by mnmin** [comment]
The frontend of the application will be responsible for the calculation that will determine the “post of the week”. 

The algorithm will look as following:

1) Use a function to determine the array of posts within the timeframe
 ``` function getPostsWithin7Days ```
2) Find the most popular post in the above array using
 ``` function getMostPopularPost ``` 
The post that has the most comments and likes combined will be returned.
3)  In the render post function we will use the splice method to remove this most popular post from the list of all posts.

**Comment by vherus** [comment]
Great stuff! Go ahead
