### ISSUE TITLE
#45 As a user, I want to see who has liked certain posts.

### ISSUE THREAD

**Issue by Noemi890** [boolean-uk/team-dev-client#355]
<img width="669" alt="Screenshot 2022-09-22 at 13 05 36" src="https://user-images.githubusercontent.com/94084046/191742444-6ab45189-b5c3-46fc-8e39-c3331a45a8db.png">

Use AvatarGroup to group some of the Users, overlapping them. Use the `max` property to display just the first 5, and the `total` property to display the number of Avatar not shown. reference(https://mui.com/material-ui/react-avatar/#grouped, https://mui.com/material-ui/react-avatar/#total-avatars )

Inside the AvatarGroup, using map, create for each Like a Avatar tag that links to the profile when clicked.

```
Example:

<AvatarGroup max={5} total={post.likes.length}>
<Avatar onClick={() => navigate(`/profile/${like.userId}`)}
```

If the total number avatar is clicked, a Dialog will appear showing all the users that liked the post. When you click on the user, you will be redirected to their profile page.

```
Example:

<Dialog>
    <List>
       <ListItemAvatar>
          <Avatar onCLick={() => navigate(`/profile/${like.userId}`)}/>
         <ListItemText primary={‘user firstName and lastName’}/>
       </ListItemAvatar>
    </List>
</Dialog>

```

**Comment by Auenc** [comment]
Looks good to me :)
