### ISSUE TITLE
#63 As a user, so I can show my appreciation of comments, I want to like them

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#367]
### Tasks
[UI example](https://excalidraw.com/#json=8T_MtKhynv5hogHoxs2Z3,N18jTO_eU45A8hwlrdBK1g)
- add a like button to the comments
- display the number of likes of the comments
- add function: click the like button to like a comments & get numbers of likes 

### Todos 
- add button element 
- add a react state for like 
- onclick function for like button when not liked: 
  - display highlighted like button 
  - send a post request to post/:postId/comment/:commentId/like, data: user
  - send a get request to post/:postId/comment/:commentId/like to get likes, run array.length to find number of likes 
  - rerender number of likes
- onclick when liked
  - unlike comment, display original like button
  - send a delete request to post/:postId/comment/:commentId/like
  - rerender number

**Comment by vherus** [comment]
What happens when the like button is clicked if that user has already liked the comment?

**Comment by deliailu27** [comment]
> What happens when the like button is clicked if that user has already liked the comment?

added in todos, unlike a comment

**Comment by vherus** [comment]
Great stuff. I don't think that delete request exists in the backend plan, let's make sure that gets added: https://github.com/boolean-uk/team-dev-server/issues/260
