### ISSUE TITLE
#60As product owner, to protect my application from sinister actors, I want to remove the role toggle on register

### ISSUE THREAD

**Issue by Noemi890** [boolean-uk/team-dev-client#370]
- Remove the toggle in the sign-up form
- Add a new button at the bottom of the profile that renders only if your role is ‘ADMIN’ called ‘account information'
- From the account information of that user, display a button underneath (rendered just for ‘ADMIN’ role) called ‘change role’.
- When the button is pressed, a Dialog will appear with a Select component inside, that lets the ‘ADMIN’ choose between all the roles available. (https://mui.com/material-ui/react-select/, https://mui.com/material-ui/react-dialog/#basic-dialog)
- In the dialog, a button called ‘update’ will be displayed underneath the Select component, clicking it will send a request to the server.
- If the admin clicks outside of the Dialog, the request will not be sent and the action will be canceled (https://mui.com/material-ui/react-click-away-listener/)
```	
Example Request:
	client
	    .patch(/user/${id}, { role })
```

<img width="615" alt="Screenshot 2022-09-27 at 11 06 25" src="https://user-images.githubusercontent.com/94084046/192498657-8e2d461a-97a8-4dc4-80ff-c0e2f8fe4b6d.png">
<img width="640" alt="Screenshot 2022-09-27 at 11 06 33" src="https://user-images.githubusercontent.com/94084046/192498659-dfaaebd0-7bbf-4862-9e24-23fb3858b332.png">
<img width="621" alt="Screenshot 2022-09-27 at 11 06 40" src="https://user-images.githubusercontent.com/94084046/192498661-821beeb8-4cfe-4a41-b868-95aef601d313.png">

**Comment by vherus** [comment]
Nice work! Approved
