### ISSUE TITLE
As a developer, so I can get visibility on the activity of the application, I want significant events users take to be shown to be in a dashboard#61

### ISSUE THREAD

**Issue by ning905** [boolean-uk/team-dev-client#375]
1- Create a DeveloperSection component which will only be displayed to a user with the DEVELOPER role.
2- Send a GET request to ‘/events’ path, and store the response in a state.
3- Create an EventList and an EventItem component, displaying the events in details.
<img width="617" alt="Screenshot 2022-09-28 at 10 11 34" src="https://user-images.githubusercontent.com/95832213/192739460-54611d51-4ce2-406f-af62-8169316266ba.png">

**Comment by ning905** [comment]
I have a question regarding where to place this developer section. 
My idea is to create a button that only developers can see in the header, and when they click the button, they will be directed to a developer page, which will display the information (such as the events) once the user passes a developer role check.

**Comment by vherus** [comment]
I love the wireframes. There's a lot more work to do on planning this feature, it's a big one.

The events should be able to be filtered by event type (e.g. admin event, user event, application error, etc.) - you'll need to spend some time thinking about the types of events that can occur.

The events should be searchable - we should be able to use a single search bar that searches events for usernames, roles, and other text content.

How will you use the data from the API to construct all of this? I'll add separate topics on the backend issue now

**Comment by ning905** [comment]
The events should be able to be filtered by event type
- use a state to track the filter
- when a type is selected, send a new GET request to the server
-- http://localhost:4000/events?type=admin

The events should be searchable
- use a state to track the input and range in the search bar
- range: username, role, content
- when the user hits 'enter' or the search icon, send a GET request with params
-- http://localhost:4000/events?content=register

The events should be sorted by createdAt time
- use a state to track the sorting, default as 'desc'
- option: most recent ('desc'), oldest ('asce')
- when the user selects the sorting, send a GET request with params
-- http://localhost:4000/events?sorting='asce'

Filter, sorting and searching can be applied together
```
useEffect(() => {
	//send GET request
}, [filter, search, sorting])
```

EventList preview
<img width="625" alt="Screenshot 2022-09-28 at 17 40 35" src="https://user-images.githubusercontent.com/95832213/192839280-bcbb6cba-64e8-4aa9-9bf4-486a11f74e9e.png">
- We decided to display the time in DateTime format rather than forms like 'less than a minute ago', to give the DEVELOPER an idea of a more accurate time of an event happening.

**Comment by Auenc** [comment]
Looks great, good job!
