### ISSUE TITLE
#33 As a teacher, so I can find students to add to my cohort, I want to search for students by name.

### ISSUE THREAD

**Issue by Noemi890** [boolean-uk/team-dev-client#382]
**This is a fix for a ticket already closed. Search Bar is not working.**

- Implement Autocomplete in the searchBar to display a list of users while typing. (https://mui.com/material-ui/react-autocomplete/#search-input)
```
<Component
  options={value}
  onKeyUp={handleKeyUp}
/>

const handleKeyUp = (e) => {
const value = e.target.value
  client
    .get(path, value)
    .then(res => setValue(res))
}
```
- Every user can be clicked, bringing the User to the profile page of the clicked user. (either with a useNavigate() or a Link component).
Reference (, https://reactrouter.com/en/main/hooks/use-navigate, https://reactrouter.com/en/main/components/link, https://mui.com/material-ui/react-autocomplete/#search-as-you-type)

<img width="636" alt="Screenshot 2022-09-28 at 17 16 58" src="https://user-images.githubusercontent.com/94084046/192832393-6be77d79-3eaa-4970-83aa-b98de94b5e0e.png">

- If the button Search is pressed, open a Dialog component with the list of users inside. Every User is clickable and redirects to the profile page.
Reference (https://mui.com/material-ui/react-dialog/)

<img width="345" alt="Screenshot 2022-09-28 at 17 17 59" src="https://user-images.githubusercontent.com/94084046/192832591-9ec733a6-a042-4501-97e1-8689947f0ee9.png">

**Comment by Auenc** [comment]
Looks good to me!
