### ISSUE TITLE
Dashboard (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#4]
> As a user,
So I can have easy access to everything,
I want to see a dashboard filled with posts after logging in.

**Requirements**
- Social media style feed of student / teacher posts

--

**GET /posts**
**Headers**
`Authorization: "Bearer <token>"`

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "posts": [
      {
        "id": int,
        "content": string,
        "author": {
          "id": int,
          "cohort_id": int | null,
          "first_name": string,
          "last_name": string,
          "role": string<"STUDENT", "TEACHER">,
        }
      }
    ]
  }
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/3

**Comment by dogezen** [comment]
Just to be 100% clear:
- Is there already an existing React Post component  or will you create that?
- What about the Feed? Ie a component for a list of Posts

- Where will the state be stored and data be fetched upon load? At the App level or in a separate component?

**Comment by dearshrewdwit** [comment]
@d-username Where is the linked PR for this?

**Comment by d-username** [comment]
https://github.com/boolean-uk/team-dev-client/pull/172
