### ISSUE TITLE
Profile view (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#5]
> As a user,
So I can compare myself to others,
I want to see their profiles.

> As a user,
So other people can see how great I am,
I want them to see my profile.

**Requirements**

- Clicking on a post author's name takes the user to a view of the author's profile information
- Clicking on a "My profile" link, or their own name on posts they have authored, takes the user to a view of their own profile information

--

**GET /user/:id**
**Headers**
`Authorization: "Bearer <token>"`

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "user": {
      "id": int,
      "cohort_id": int | null,
      "first_name": string,
      "last_name": string,
      "email": string,
      "role": string<"STUDENT", "TEACHER">,
      "biography": string | null,
      "github_url": string | null
    }
  }
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/5

**Comment by sigristarisa** [comment]
Worked on the steps of how we could accomplish the task (see Notion).
Added screenshots and code in the Notion page that might be helpful as a reference and interface idea.
[Notion: Client Profile view](https://bubble-walkover-60b.notion.site/Profile-View-client-0f1ed618aed443f599f24982fab75ebc)
