### ISSUE TITLE
Add user to cohort (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#9]
> As a teacher,
So I can organise our students,
I want to assign students to a cohort.

**Requirements**

- "Cohort" input field on user profiles where you can manually enter a cohort ID
- Submit button
- Only users with a `role` of `"TEACHER"` can see / use this form

--

**PATCH /user/:id**
**Headers**
`Authorization: "Bearer <token>"`

```json
{
  "cohort_id": int | null
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/8

**Comment by PBara7a** [comment]
![image](https://user-images.githubusercontent.com/72984740/175935450-16996584-9f21-4718-8120-8649312b5018.png)
